export const TeamNames: string[] = [
    'The Waiver Wire',
    'Rockstar bookworms',
    'That Better Team',
    'Recreational Hazard',
    'Don’t stop quizieving',
    'Vandelay Industries',
    'We Got the Runs',
    'Backhanded Compliments',
    'Son of Pitch',
    'Menace to Sobriety',
    'The Big Egos',
    'The Human Targets',
    'Fargo Woodchippers',
    'The Has - Beens',
    'Mad Thrashers',
    'The Pace Makers',
    'Not Fast But Furious',
    'Attack of the Invisible Ninja',
    'Running On Empty',
    'Corporate Punishment',
    'Club Win',
    'Big Dudes Scared Shoes',
    'Fifty Shades of answers',
    'Hustle & Flo',
    'Game of Throw Ins',
    'Beer Pressure',
    'Game of Throws',
    'It’s Always Runny in Philadelphia',
    'Zombie Warfare',
    'Twisted Blisters',
    'The Skeptics',
    'The Last Place Lolipops',
    'Mental Toss Flycoons',
    'The Baha Badboys',
    'The Real Replacements',
    'Shocked the Cynics',
    'The “B” Squad',
    'Snickerdoodles',
    'Hellacious Hackers',
    'Razzle Dazzle',
    'The Fast and the Curious',
    'Geeks and Freaks',
    'Financial Wizards',
    'The Digital Divas',
    'Masters of Mayhem',
    'Invincibles',
    'P&L Ponies',
    'The Credit Crush',
    'The Terrible Tycoons',
    'Math Mavericks',
    'Number Crunchers',
    'The Red Rainmakers',
    'The Brain Trust',
    'Vision quest',
    'Executive Authority',
    'Quests R Us',
];
